# Generated by Django 2.1.5 on 2019-10-11 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('address', models.CharField(default=None, max_length=200)),
                ('city', models.CharField(default=None, max_length=200)),
                ('state', models.CharField(default=None, max_length=200)),
                ('zipcode', models.CharField(default=None, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('bedrooms', models.IntegerField(default=None)),
                ('guests', models.IntegerField(default=None)),
                ('lastminute', models.CharField(default=None, max_length=20)),
                ('gender', models.CharField(default=None, max_length=20)),
                ('kidfriendly', models.CharField(default=None, max_length=20)),
                ('smokingallow', models.CharField(default=None, max_length=20)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
