# Generated by Django 2.1.5 on 2019-08-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_4n',
            new_name='photo_4',
        ),
    ]
